### ISSUE TITLE
Improve file input field

### ISSUE THREAD

**Issue by tuttieee** [asha-nepal/AshaFusionCross#594]
Current design:
<img width="262" alt="2018-02-12 18 55 32" src="https://user-images.githubusercontent.com/3135397/36091207-556d2728-1026-11e8-9f29-e4e026cd13e9.png">

To do:
- To improve the appearance by applying bulma CSS( https://bulma.io/documentation/form/file/ )
  - Applying CSS styles to https://github.com/asha-nepal/AshaFusionCross/blob/master/src/web/forms/fields/AttachmentInput.js#L35
- To improve the behavior to be able to accept a file by drag and drop
  - Updating the code above to work with DnD functionality

**Comment by elephantgloves** [comment]
Addressed in pull request: #694

**Comment by elephantgloves** [comment]
Please check part 1 first of Bulma CSS styling.
(TODO: DND functionality)

**Comment by elephantgloves** [comment]
Implemented DnD functionality as React Component! Please check.
