### ISSUE TITLE
Remove unnecessary fields from Pharping version

### ISSUE THREAD

**Issue by tuttieee** [asha-nepal/AshaFusionCross#654]
Following fields implemented on Pharping version are now not used in practice and to be deleted
* `Guardian's name`
* `Relationship`
* `Ethnicity`

Pharping version is on `release/pharping` branch which was forked from `master` branch.

-----
TODO:

1. Check out to `release/pharping` branch
2. Create new feature branch with name such as `feature/pharping/remove-unnecessary-patient-fields` and check out to that branch.
3. Do work on the forked feature branch.
  * Edit `src/store/reducers/dform/initial/styles.json` to remove the fields above
4. Add the file and commit.
5. Push the branch to github and create PullRequest. The PullRequest must be from `feature/pharping/remove-unnecessary-patient-fields` to `release/pharping`. **Not to `master`**. Please note that.

-----
@hup-en 
The workflow described above is basically same to what we talked except the difference of the PR's target branch.
Please ask anything if you have trouble, thanks.

**Comment by hup-en** [comment]
It is showing other commit lists though I didn't change anything besides.
