### ISSUE TITLE
Ordering system

### ISSUE THREAD

**Issue by tuttieee** [asha-nepal/AshaFusionCross#659]
- [x] Add pathology test list to "physician" form
  - Doctor can select necessary tests
- [x] Show only selected tests in "pathology" form

**Comment by hup-en** [comment]
Any planning on this topic please?

**Comment by tuttieee** [comment]
I think the below will work.

1. Add a new `checkgroup` component to "physician" form in order for doctors to select and order tests like this:
```json

        {
          "field": "test_order",
          "label": "Test Order",
          "class": "checkgroup",
          "show": "plan:test",
          "options": [
            { "id": "bs", "label": "Blood Sugar" },
            { "id": "pathology.haematology.hemoglobin", "label": "Hemoglobin (Hb)" },
            { "id": "pathology.haematology.pcv", "label": "PCV" }
            ...(all the rest)...
          ]
        },
```
By this, physician can select necessary tests like this:
<img width="860" alt="2018-08-26 17 20 24" src="https://user-images.githubusercontent.com/3135397/44626268-5a2c4d80-a954-11e8-81fc-ac2c8eab40b1.png">
For example, in this case, `"test_order"` field in this record has a value like `["bs", "pathology.haematology.pcv"]`.

2. Add `show` prop to each field in "Pathology" form like below:
```json
                ...
                {
                  "field": "bs",
                  "label": "Blood sugar",
                  "show": "test_order:bs",
                  ...
                },
                {
                  "field": "pathology.haematology.hemoglobin",
                  "label": "Hemoglobin (Hb)",
                  "show": "test_order:pathology.haematology.hemoglobin",
                  ...
                },
                {
                  "field": "pathology.haematology.pcv",
                  "label": "PCV",
                  "show": "test_order:pathology.haematology.pcv",
                  ....
                }
                ...
```
By this, each field in "Pathology" form appears and disappears accordingly to the selection of "test_order" component defined in 1.

**Comment by tuttieee** [comment]
I updated assignee because this issue is referred from #667 and both may be done at the same time.

**Comment by elephantgloves** [comment]
Done, together with 667. Please check both.
