### ISSUE TITLE
Show the total number of patients, records on Stats page

### ISSUE THREAD

**Issue by tuttieee** [asha-nepal/AshaFusionCross#669]
# What should be implemented?
Number of patients and records should be printed on Stats page.

# Background / Necessary knowledge
## Usage of Stats page
1. Go to stats page
<img width="847" alt="2018-07-12 2 55 02" src="https://user-images.githubusercontent.com/3135397/42590562-1d665d3a-857f-11e8-956b-47e75532d653.png">
2. Load data
<img width="847" alt="2018-07-12 2 57 03" src="https://user-images.githubusercontent.com/3135397/42590626-52f8e030-857f-11e8-92b7-ae7cba3f92fa.png">

## Where is patient / record data stored?
Almost all data handled by ASHA fusion is stored in [redux](https://redux.js.org/)'s store.
You should understand the concept of redux (and how redux is connected to React, probably).

After you understand redux, you can access to patient / record data list stored in `state.patientList` and `state.recordList`. The definition of reducers is here: https://github.com/asha-nepal/AshaFusionCross/blob/release/pharping-camp/src/store/reducers/index.js#L40

**Comment by elephantgloves** [comment]
PR sent, please check.
